# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

name: "RPM Build"
description: "Build RPMs in preconfigured SL7 docker image"
runs:
  using: "docker"
  image: "Dockerfile"
  #Need to add the following to the docker-run invocation not to fail mock:
  #options: --cap-add=SYS_ADMIN
