# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

FROM mambelli/gwms-ci-sl7
COPY entrypoint.sh /entrypoint.sh
RUN groupadd -g 500 glideinwms-ci
RUN useradd -u 500 -g 500 glideinwms-ci
USER glideinwms-ci
ENTRYPOINT ["/entrypoint.sh"]
