#!/bin/bash

# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
. "$script_dir/blah_common_submit_functions.sh"

bls_submit_args_prefix="#SBATCH"
bls_parse_submit_options "$@"

sfapi_import_blah_environment() {
    local env_payload="${bls_opt_environment:-}"
    if [ "x$env_payload" = "x" ]; then
        env_payload="${bls_opt_envir:-}"
    fi
    if [ "x$env_payload" = "x" ]; then
        return
    fi

    while IFS= read -r env_line; do
        env_line="${env_line//\\/}"
        env_line="${env_line#;}"
        for env_var in $env_line; do
            case "$env_var" in
                SFAPI_AUTH_MODE=*|SFAPI_AUTH_FILE=*|SFAPI_PYTHON=*|SFAPI_VENV=*|SFAPI_RESOURCE=*|SFAPI_TRANSFER_MACHINE=*|SFAPI_STATE_DIR=*|SFAPI_USERNAME=*|NERSC_USERNAME=*|SFAPI_ACCOUNT=*|SFAPI_PROJECT=*|SFAPI_QOS=*|SFAPI_CONSTRAINT=*)
                    export "$env_var"
                    ;;
            esac
        done
    done < <(printf '%s\n' "$env_payload" | sed 's/\\ /\n/g; s/;/\n/g')
}

sfapi_import_blah_environment
# shellcheck disable=SC1091
. "$script_dir/sfapi_setup.sh" || exit 1
bls_setup_temp_files

sfapi_add_csv() {
    local current="$1"
    local item="$2"
    if [ -z "$item" ] || [ "$item" = "/dev/null" ]; then
        echo "$current"
    elif [ -z "$current" ]; then
        echo "$item"
    else
        echo "$current,$item"
    fi
}

sfapi_emit_directive() {
    local option="$1"
    local value="$2"
    if [ -n "$value" ]; then
        printf '#SBATCH %s=%s\n' "$option" "$value" >> "$bls_tmp_file"
    fi
}

sfapi_abs_path() {
    local path="$1"
    if [ -z "$path" ] || [ "$path" = "/dev/null" ]; then
        return
    fi
    if [ "${path:0:1}" = "/" ]; then
        echo "$path"
    else
        echo "${bls_opt_workdir}/${path}"
    fi
}

sfapi_add_file_list() {
    local current="$1"
    local list_file="$2"
    local file_path=""

    if [ -n "$list_file" ] && [ -r "$list_file" ]; then
        while IFS= read -r file_path; do
            current="$(sfapi_add_csv "$current" "$(sfapi_abs_path "$file_path")")"
        done < "$list_file"
    fi

    echo "$current"
}

sfapi_emit_environment() {
    if [ "x$bls_opt_environment" != "x" ]; then
        echo ""
        echo "# Setting the environment:"
        eval "env_array=($bls_opt_environment)"
        for env_var in "${env_array[@]}"; do
            case "$env_var" in
                SFAPI_*=*) continue ;;
            esac
            echo "export \"$env_var\""
        done
    elif [ "x$bls_opt_envir" != "x" ]; then
        echo ""
        echo "# Setting the environment:"
        echo "$(echo ";$bls_opt_envir" | sed -e 's/;[^=]*;/;/g' -e 's/;[^=]*$//g' | sed -e 's/;\([^=]*\)=\([^;]*\)/;export \1="\2"/g' | awk 'BEGIN { RS = ";" } ; { print $0 }')"
    fi
}

{
    echo "#!/bin/bash"
    echo "# SFAPI SBATCH wrapper generated by $(basename "$0") on $(date)"
} > "$bls_tmp_file"

sfapi_emit_directive "--account" "${bls_opt_project:-${SFAPI_ACCOUNT:-${SFAPI_PROJECT:-}}}"
if [ -n "$bls_opt_runtime" ]; then
    sfapi_emit_directive "--time" "$((bls_opt_runtime / 60))"
fi
sfapi_emit_directive "--mem" "$bls_opt_req_mem"
sfapi_emit_directive "--qos" "${SFAPI_QOS:-$bls_opt_queue}"
sfapi_emit_directive "--constraint" "$SFAPI_CONSTRAINT"
sfapi_emit_directive "--nodes" "$bls_opt_hostnumber"
sfapi_emit_directive "--ntasks" "$bls_opt_mpinodes"

[ -z "$bls_opt_gpunumber" ] || [ -z "$bls_opt_gpumodel" ] || echo "#SBATCH --gres=gpu:${bls_opt_gpumodel}:${bls_opt_gpunumber}" >> "$bls_tmp_file"
[ -z "$bls_opt_gpunumber" ] || [ -n "$bls_opt_gpumodel" ] || echo "#SBATCH --gres=gpu:${bls_opt_gpunumber}" >> "$bls_tmp_file"
[ -n "$bls_opt_gpunumber" ] || [ -z "$bls_opt_gpumodel" ] || echo "#SBATCH --gres=gpu:${bls_opt_gpumodel}:1" >> "$bls_tmp_file"

bls_set_up_local_and_extra_args

sfapi_input_files_csv=""
sfapi_command="$bls_opt_the_command"
if [ "$bls_opt_stgcmd" = "yes" ]; then
    sfapi_input_files_csv="$(sfapi_add_csv "$sfapi_input_files_csv" "$(sfapi_abs_path "$bls_opt_the_command")")"
    sfapi_command="./$(basename "$bls_opt_the_command")"
fi

sfapi_stdin_remote=""
if [ -n "$bls_opt_stdin" ] && [ "$bls_opt_stdin" != "/dev/null" ]; then
    sfapi_input_files_csv="$(sfapi_add_csv "$sfapi_input_files_csv" "$(sfapi_abs_path "$bls_opt_stdin")")"
    sfapi_stdin_remote="$(basename "$bls_opt_stdin")"
fi

sfapi_input_files_csv="$(sfapi_add_file_list "$sfapi_input_files_csv" "$bls_opt_inputflstring")"

{
    sfapi_emit_environment
    echo ""
    echo "# Command to execute:"
    if [ "$bls_opt_stgcmd" = "yes" ]; then
        echo "if [ ! -x \"$sfapi_command\" ]; then chmod u+x \"$sfapi_command\"; fi"
    fi
    if [ -n "$sfapi_stdin_remote" ]; then
        echo "$sfapi_command $bls_arguments < \"$sfapi_stdin_remote\""
    else
        echo "$sfapi_command $bls_arguments"
    fi
    echo "exit \$?"
} >> "$bls_tmp_file"

bls_save_submit

sfapi_result="$("$SFAPI_PYTHON" "$SFAPI_HELPERS_DIR/sfapi_helpers.py" submit \
    --job-name "$bls_tmp_name" \
    --input-files "$sfapi_input_files_csv" \
    --script "$bls_tmp_file")"
sfapi_retcode=$?
if [ "$sfapi_retcode" -ne 0 ]; then
    echo "$sfapi_result" >&2
    bls_wrap_up_submit
    exit "$sfapi_retcode"
fi

case "$sfapi_result" in
    SFAPI_RESULT:*) ;;
    *)
        echo "Unexpected SFAPI submit result: $sfapi_result" >&2
        bls_wrap_up_submit
        exit 1
        ;;
esac

sfapi_payload="${sfapi_result#SFAPI_RESULT:}"
sfapi_jobid="${sfapi_payload%%:*}"
sfapi_payload="${sfapi_payload#*:}"
sfapi_remote_stdout="${sfapi_payload%%:*}"
sfapi_remote_stderr="${sfapi_payload#*:}"
sfapi_remote_dir="$(dirname "$sfapi_remote_stdout")"
sfapi_date="$(date +%Y%m%d)"
sfapi_state_file="$SFAPI_STATE_DIR/${sfapi_date}_${sfapi_jobid}"

mkdir -p "$SFAPI_STATE_DIR"
{
    echo "meta::auth_mode:${SFAPI_AUTH_MODE:-}"
    echo "meta::auth_file:${SFAPI_AUTH_FILE:-}"
    echo "meta::resource:${SFAPI_RESOURCE:-}"
    echo "meta::transfer_machine:${SFAPI_TRANSFER_MACHINE:-}"
    echo "meta::python:${SFAPI_PYTHON:-}"
    echo "meta::venv:${SFAPI_VENV:-}"
    echo "meta::username:${SFAPI_USERNAME:-}"
    echo "meta::nersc_username:${NERSC_USERNAME:-}"
    echo "# type::<local file on submit host>:<remote file to retrieve via sfapi>"
    if [ -n "$bls_opt_stdout" ] && [ "$bls_opt_stdout" != "/dev/null" ]; then
        echo "stdout::$(sfapi_abs_path "$bls_opt_stdout"):${sfapi_remote_stdout}"
    fi
    if [ -n "$bls_opt_stderr" ] && [ "$bls_opt_stderr" != "/dev/null" ]; then
        echo "stderr::$(sfapi_abs_path "$bls_opt_stderr"):${sfapi_remote_stderr}"
    fi

    if [ -n "$bls_opt_outputflstring" ] && [ -r "$bls_opt_outputflstring" ]; then
        exec 5< "$bls_opt_outputflstring"
        if [ -n "$bls_opt_outputflstringremap" ] && [ -r "$bls_opt_outputflstringremap" ]; then
            exec 6< "$bls_opt_outputflstringremap"
        fi
        while IFS= read -r output_remote <&5; do
            if [ -n "$output_remote" ]; then
                output_local="$output_remote"
                if [ -n "$bls_opt_outputflstringremap" ] && [ -r "$bls_opt_outputflstringremap" ]; then
                    IFS= read -r output_local <&6
                    [ -n "$output_local" ] || output_local="$output_remote"
                fi
                echo "output::$(sfapi_abs_path "$output_local"):${sfapi_remote_dir}/$(basename "$output_remote")"
            fi
        done
        exec 5<&-
        if [ -n "$bls_opt_outputflstringremap" ] && [ -r "$bls_opt_outputflstringremap" ]; then
            exec 6<&-
        fi
    fi
} > "$sfapi_state_file"

echo "BLAHP_JOBID_PREFIXsfapi/${sfapi_date}/${sfapi_jobid}"
bls_wrap_up_submit
