# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# Adds <issue_type> label if issue body contains certain words (when based on the issue template)

# regular expressions for labeling priority of the issue is listed in this block
Critical:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?([Cc]ritical|[Uu]rgent)\]?'
High:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Hh]igh\]?'
Medium:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Mm]edium\]?'
Low:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Ll]ow\]?'

# regular expressions for labeling issue type is listed in this block
BUG:
  - "bug"
FEATURE:
  - "feature( request)?"
# ENHANCEMENT:
# IDEA:
# QUESTION:
# SUPPORT:

# regular expressions for labeling stakeholders for an issue is listed in this block
cms:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b(?:CMS|Cms|cms)\b)'
dune:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b(?:DUNE|Dune|dune)\b)'
factoryops:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b[Ff]actory[Oo]ps\b)'
fermilab:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b[Ff]ermilab\b)'
fife:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b(?:FIFE|Fife|fife)\b)'
hepcloud:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b[Hh][Ee][Pp][Cc][Ll][Oo][Uu][Dd]\b)'
# Historically IGWN had the LIGO name
igwn:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b(?:IGWN|Igwn|igwn|LIGO|Ligo|ligo)\b)'
osg:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?.*(\b(?:OSG|[Oo]sg)\b)'
# if new stakeholders need to be included, add them here
other-sh:
  - 'Stakeholders: *(?:Concerned stakeholder\(s\) *)?\[?((?:\b(?!Concerned stakeholder|CMS|Cms|cms|[Ff]actory[Oo]ps|[Ff]ermilab|FIFE|Fife|fife|[Hh][Ee][Pp][Cc][Ll][Oo][Uu][Dd]|IGWN|Igwn|igwn|LIGO|Ligo|ligo|OSG|[Oo]sg)\b)[^, \n\]]+)\]?'

# regular expressions for labeling affected components for an issue is listed in this block
frontend:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Ff]rontend(?! [Mm]onitoring)\b)'
factory:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Ff]actory(?! [Mm]onitoring)\b)'
glidein:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Gg]lidein\b)'
documentation:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Dd]ocumentation\b)'
ci-testing:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b(CI|ci|[Tt]esting)\b)'
release:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Rr]elease\b)'
factory-mon:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Ff]actory(?= [Mm]onitoring)\b)'
frontend-mon:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?.*(\b[Ff]rontend(?= [Mm]onitoring)\b)'
other-comp:
  - 'Components: *(?:The affected component,? (?:due to this bug|if any, from this feature) *)?\[?((?:\b(?!The affected|[Ff]rontend [Mm]onitoring|[Ff]actory|[Gg]lidein|[Dd]ocumentation|(CI|ci|[Tt]esting)|[Rr]elease|[Ff]actory [Mm]onitoring|[Ff]rontend)\b)[^, \n\]]+)\]?'
# This line flags other names, but will not work if they are in the list after known ones
# if there are any other possible components that need to be added to the list above, add them here when needed

# TODO: regular expressions for labeling release info for an issue is listed in this block
# 3.9.5:
# 3.9.6:
# 3.11:
