# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# Adds <issue_type> label if issue body contains certain words (when based on the issue template)

# regular expressions for labeling priority of the issue is listed in this block
Critical:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?([Cc]ritical|[Uu]rgent)\]?'
High:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Hh]igh\]?'
Medium:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Mm]edium\]?'
Low:
  - 'Priority: *(Priority level (of|for) this (bug|feature) *)?\[?[Ll]ow\]?'

# regular expressions for labeling issue type is listed in this block
BUG:
  - "bug"
FEATURE:
  - "feature( request)?"
# ENHANCEMENT:
# IDEA:
# QUESTION:
# SUPPORT:

# regular expressions for labeling stakeholders for an issue is listed in this block
cms:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?(CMS|Cms|cms)\]?'
factoryops:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?([Ff]actory[Oo]ps)\]?'
fermilab:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?([Ff]ermilab)\]?'
fife:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?(FIFE|Fife|fife)\]?'
# Historically IGWN had the LIGO name
igwn:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?(IGWN|Igwn|igwn|LIGO|Ligo|ligo)\]?'
osg:
  - 'Stakeholder: *(Concerned stakeholder\(s\) *)?\[?(OSG|Osg|osg)\]?'
# if new stakeholders need to be included, add them here

# regular expressions for labeling affected components for an issue is listed in this block
frontend:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Ff]rontend(?! [Mm]onitoring)\]?'
factory:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Ff]actory(?! [Mm]onitoring)\]?'
glidein:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Gg]lidein\]?'
documentation:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?([Dd]ocumentation)\]?'
ci-testing:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?(CI|ci|[Tt]esting)\]?'
release:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Rr]elease\]?'
factory-mon:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Ff]actory(?= [Mm]onitoring)\]?'
frontend-mon:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?[Ff]rontend(?= [Mm]onitoring)\]?'
other:
  - 'Component: *(The affected component,? (due to this bug|if any, from this feature) *)?\[?(?![Ff]rontend(?= [Mm]onitoring)|[Ff]actory(?! [Mm]onitoring)|[Gg]lidein|[Dd]ocumentation|(CI|ci|[Tt]esting)|[Rr]elease|[Ff]actory(?= [Mm]onitoring)|[Ff]rontend(?= [Mm]onitoring))\]?'
# if there are any other possible components that need to be added to the list above, add them here when needed

# TODO: regular expressions for labeling release info for an issue is listed in this block
# 3.9.5:
# 3.9.6:
# 3.11:
