# File : .pep8speaks.yml
# pep8speaks is a GitHub app, https://pep8speaks.com/

scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle  # Other option is flake8

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 120  # Default is 79 in PEP 8
    disable:
        - unsubscriptable-object
    ignore:  # Errors and warnings to ignore
        - E111  # E111 indentation is not a multiple of four
          # E121  # E121 continuation line under-indented for hanging indent
          # E123  # E123 closing bracket does not match indentation of opening bracket's line
          # # E126 continuation line over-indented for hanging indent
          # # E221 multiple spaces before operator
        - E225  # E225 missing whitespace around operator
        - E226  # E226 missing whitespace around arithmetic operator
        - E228  # E228 missing whitespace around modulo operator
        - E231  # E231 missing whitespace after ','
          # E251 unexpected spaces around keyword / parameter equals
        - E261  # E261 at least two spaces before inline comment
        - E265  # E265 block comment should start with '# '
        - E302  # E302 expected 2 blank lines, found 1
        # E303 too many blank lines (3)
        # E402 module level import not at top of file
        - E501  # E501 line too long
        # E704 multiple statements on one line (def)
        # E731  # do not assign a lambda expression, use a def
        # E741  # ambiguous variable name
        # C406  # Unnecessary list literal - rewrite as a dict literal.
        - W291  # W291 trailing whitespace
        - W293  # W293 blank line contains whitespace
        # W504 line break after binary operator

# flake8:
#    max-line-length: 120
#    ignore:  # Errors and warnings to ignore
#      - E501 # line too long (90 > 79 characters)
#      - E303 # too many blank lines (2)
#      - E302 # expected 2 blank lines, found 1
#      - E261 # at least two spaces before inline comment
#      - E265 # block comment should start with '# '
#
#    exclude: []
#    count: True
#    show-source: True
#    statistics: True

    
no_blank_comment: True  # If True, no comment is made on PR without any errors.
descending_issues_order: False  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hello @{name}! Thanks for opening this PR. "
                # The keyword {name} is converted into the author's username
        footer: "Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)"
                # The messages can be written as they would over GitHub
    updated:  # Messages when new commits are added to the PR
        header: "Hello @{name}! Thanks for updating this PR. "
        footer: ""  # Why to comment the link to the style guide everytime? :)
    no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: "

