#!/bin/sh

#
# chkconfig: 3 90 99
# description: GlideinPilot
#
# Starts the glideinWMS Pilot
#

case $1 in
'start')
    echo "Starting up GlideinPilot"
    ulimit -n 131072
    /usr/sbin/PilotLauncher
    ;;

'stop')
    echo "Not doing anything... we don't care, since the Image will start clean next time"
    ;;

*)
    echo "Usage: GlideinPilot {start|stop}"
    ;;

esac
