#! /bin/sh

#
# chkconfig: 3 90 99
# description: GlideinPilot
#
# Starts the glideinWMS Pilot
#

case $1 in
'start')
    # make $OSG_APP
    mkdir -p /mnt/app
    # make $OSG_DATA
    mkdir -p /mnt/data
    # make the CMS directory
    mkdir -p /mnt/app/cmssoft
    # put a symbolic link in $OSG_DATA/cmssoft to point to the CERN VM FS mount point for CMS 
    ln -s /opt/cms /mnt/app/cmssoft/cms

    echo "Starting up GlideinPilot"
    ulimit -n 131072
    /usr/sbin/PilotLauncher
    ;;

'stop')
    echo "Not doing anything... we don't care, since the Image will start clean next time"
    ;;

*)
    echo "Usage: GlideinPilot {start|stop}"
    ;;

esac
