#!/bin/sh

# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

# Description:
#   This is a shell script wrapper for pychirp.py


if [ -f "$1" ]; then
    glidein_config="$1"

    # import add_config_line function
    add_config_line_source=$(grep -m1 '^ADD_CONFIG_LINE_SOURCE ' "$glidein_config" | cut -d ' ' -f 2-)
    source "$add_config_line_source"

    error_gen=$(gconfig_get ERROR_GEN_PATH "$glidein_config")
fi

[ -n "$error_gen" ] && CONFIG=TRUE

if [ -n "$CONFIG" ]; then
    "$error_gen" -ok "libtest.sh" "WN_Resource" "pychirp wrapper"
else
    exec "$(dirname "$0")"/gwms-python -m htchirp "$@"
    echo "$0: failed to execute the python condor_chirp" >&2
    exit 1
fi
