FROM mambelli/gwms-sl7
RUN yum install -y bats
COPY entrypoint.sh /entrypoint.sh
RUN groupadd -g 500 glideinwms-ci
RUN useradd -u 500 -g 500 glideinwms-ci
USER glideinwms-ci
ENTRYPOINT ["/entrypoint.sh"]
