#!/bin/bash
# file: frontend_condorpassword
# purpose: scans ${req_dir} for new request_file_name (s)
#          creates htcondor password in /etc/condor/passwords.d/request_file_name
# author: Dennis Box, dbox@fnal.gov




fe_user=$(stat --format "%U" /etc/gwms-frontend/frontend.xml)
fe_group=$(stat --format "%G" /etc/gwms-frontend/frontend.xml)
fe_home=$(bash -c "cd ~$(printf %q ${fe_user}) && pwd")

htc_pwd_dir=/etc/condor/passwords.d
gwms_pwd_dir="${fe_home}/passwords.d"
gwms_tkn_dir="${fe_home}/tokens.d"

req_dir="${fe_home}/password-requests.d"


for request in $(find "${req_dir}" -print) ; do
    if [ "${request}" = "${req_dir}" ] ;then
	continue
    fi
    key="$(basename ${request})"
    htc_pwd_date=0
    if [ -e "${htc_pwd_dir}/${key}" ]; then
        htc_pwd_date=$(stat --format '%Y' "${htc_pwd_dir}/${key}")
    fi
    req_date=$(stat --format '%Y' "${request}")
    #echo $request $req_date $htc_pwd_date 
    if [ $req_date -gt  $htc_pwd_date ]; then
       echo updating ${htc_pwd_dir}/${key} 
       /usr/sbin/condor_store_cred -i "${gwms_pwd_dir}/${key}"  -u "${fe_user}@${HOSTNAME}" -f "${htc_pwd_dir}/${key}" add
    fi

done

