#!/bin/bash
# file: frontend_condorpassword
# purpose: scans ${req_dir} for new request_file_name (s)
#          creates htcondor password in /etc/condor/passwords.d/request_file_name
#          copies password to ${gwms_pwd_dir}/request_file_name
# author: Dennis Box, dbox@fnal.gov

fe_user=$(stat --format "%U" /etc/gwms-frontend/frontend.xml)
fe_group=$(stat --format "%G" /etc/gwms-frontend/frontend.xml)
fe_home=$(bash -c "cd ~$(printf %q ${fe_user}) && pwd")

htc_pwd_dir=/etc/condor/passwords.d
gwms_pwd_dir="${fe_home}/passwords.d"
gwms_tkn_dir="${fe_home}/tokens.d"

req_dir="${fe_home}/password-requests.d"

if [ ! -d "${req_dir}" ]; then
    mkdir -p "${gwms_pwd_dir}"
    mkdir -p "${gwms_tkn_dir}"
    mkdir -p "${req_dir}"
    chown -R "${fe_user}:${fe_group}"  "${gwms_pwd_dir}"
    chown -R "${fe_user}:${fe_group}"  "${gwms_tkn_dir}"
    chown -R "${fe_user}:${fe_group}" "${req_dir}" 
fi

for request in $(find "${req_dir}" -print) ; do
    if [ "${request}" = "${req_dir}" ] ;then
	continue
    fi
    key="$(basename ${request})"
    openssl rand -base64 64 | /usr/sbin/condor_store_cred -u "${fe_user}@${HOSTNAME}" -f "${htc_pwd_dir}/${key}" add > /dev/null 2>&1
    if [ ! "${key}" = "POOL" ]; then
        /bin/cp "${htc_pwd_dir}/${key}" "${gwms_pwd_dir}"
        chown "${fe_user}:${fe_group}" "${gwms_pwd_dir}/${key}"
    fi
    if [ -e "${gwms_pwd_dir}/${key}" ]; then
        /bin/rm -f  "${request}"
    fi
done

