# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

name: "Unit Tests"
description: "Run unit tests in preconfigured docker image"
runs:
  using: "docker"
  image: "docker://glideinwms/gwms-ci-el9"
  entrypoint: "/gha_ci_runner.sh"
  args: ["pyunittest", "runtest", "-vI", "pyunittest", "-a"]
