FROM mambelli/gwms-ci-sl7
#FROM mambelli/gwms-sl7
#RUN /usr/bin/yumalldeps.sh -i -y "--enablerepo=osg-contrib" glideinwms-factory glideinwms-vofrontend
COPY entrypoint.sh /entrypoint.sh
RUN groupadd -g 500 glideinwms-ci
RUN useradd -u 500 -g 500 glideinwms-ci
USER glideinwms-ci
ENTRYPOINT ["/entrypoint.sh"]
