# SPDX-FileCopyrightText: 2009 Fermi Research Alliance, LLC
# SPDX-License-Identifier: Apache-2.0

on: [pull_request, push]

jobs:
  bats_job:
    runs-on: ubuntu-latest
    name: A job to run BATS tests
    steps:
      - name: Sparse checkout
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          # Following code is based on logs of actions/checkout@v, with sparseCheckout stuff inserted in the middle
          echo "Syncing repository: $GITHUB_REPOSITORY"
          echo "Working directory is '$(pwd)' GITHUB_WORKSPACE=$GITHUB_WORKSPACE BRANCH=$BRANCH"
          git version
          git init $GITHUB_WORKSPACE
          git remote add origin https://github.com/$GITHUB_REPOSITORY
          git config --local gc.auto 0
          # Now interesting part
          git config core.sparseCheckout true
          # Add here contents of sparse-checkout line by line
          echo ".github" >> .git/info/sparse-checkout
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=10 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B ${BRANCH} refs/remotes/origin/${BRANCH}
        id: sparse-checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "glideinwms"
      - name: bats test action step
        id: bats
        uses: ./.github/actions/bats-in-docker
      - name: Archive bats log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: logs.tar.bz2
          retention-days: 14
